# name of the dataset
DATASET_TITLE="wippolder"
# CRS used internally by geoflow during reconstruction. Should be a projected system with units in meter.
GF_PROCESS_CRS="EPSG:7415"
# CRS of the output files
OUTPUT_CRS="EPSG:7415"
# building object identifier. This is should be an attribute in the input footprint file. The default "OGR_FID" works in case you do not have an identifier attribute available.
BID_ATTRIBUTE="identificatie"
# size of the output tiles in meters. The input is cut into square tiles of TILE_SIZE x TILE_SIZE, mainly to prevent the output files from becoming too large to visualise.
TILE_SIZE=10000.0
# path to the input footprint source. Most vector formats are accepts, including GPKG, shapefile. Must have a valid CRS set.
INPUT_FOOTPRINT_SOURCE="test-data/wippolder.gpkg"
# path to input point clouds in LAS/LAZ format. Either a space separated string with las files, or a folder containing LAS files (all .las/.laz filed in the folder are read). Must have a valid CRS set.
INPUT_LAS_FILES="test-data/wippolder.las"
# Override EPSG code of INPUT_LAS_FILES
INPUT_LAS_EPSG="EPSG:7415"

# point cloud source, becomes the "source" attribute in the output files
U_SOURCE="AHN3"
# point cloud survey date, becomes the "survey_data" attribute in the output files
U_SURVEY_DATE="2014"


## Reconstruction Parameters with values tuned for AHN3 data (8 ppsm) 

# [meter] maximum distance from candidate points to line during line fitting procedure. Higher values offer more robustness against irregular lines, lower values give more accurate lines (ie. more closely wrapping around point cloud).
line_detect__epsilon=0.4
# [meter] minimum distance for merging adjecent roofparts in generalisation from LoD2.2 to LoD1.3. Lower values will result in more roof levels in the LoD1.3 model. Default of 3 meter is chosen
lod13__step_height=3.0
# [no unit] weight used for data term in graph-cut optimisation of roofpartition. Higher values will yield buildings that are closer to the input pointcloud. Lower values will yield simpler reconstruction outputs (ie. models with less faces, vertices and edges).
optimisation_data_term=7.0
# [meter] maximum distance from candidate points to plane during plane fitting procedure. Higher values offer more robustness against oversegmentation in plane detection, lower values give more planes that are closer to the point cloud.
plane_detect__epsilon=0.2
# [no unit] number of points used in nearest neighbour queries during plane detection
plane_detect__k=15
# [no unit] minimum number of points required for detecting a plane
plane_detect__min_points=15
# [no unit] maximum allowed angle between points inside the same detected plane. This value is compared to the dot product between two unit normals. Eg. 0 means 90 degrees (orthogonal normals), and 1.0 means 0 degrees (parallel normals)
plane_detect__normal_angle=0.75
# [meter] distance used in computing alpha-shape of detected plane segments prior to line detection. Higher values offer more robustness against irregular lines, lower values give more accurate lines (ie. more closely wrapping around point cloud).
thres_alpha=0.25
# [meter] maximum distance to merge lines during line regularisation (after line detection). Approximately parallel lines that are closer to each other than this threshold are merged. Higher values yield more regularisation, lower values preserve more finer details.
thres_reg_line_dist=0.5
# [meter] extension of regularised lines prior to optimisation. Used to compensate for undetected parts in the roofpart boundaries. Use higher values when the input pointcloud is less dense. However, setting this too high can lead to unrealistic reconstruction results.
thres_reg_line_ext=1.5
# [boolean, no unit] Set to true to activate the procedure that clips parts from the input footprint wherever patches of ground points are detected. May cause irregular outlines in reconstruction result.
clip_ground=true